### ISSUE TITLE
添加判断临时目录和保存目录是否满

### ISSUE THREAD

**Issue by onct** [CHN-STUDENT/WebServerAutoBackup#10]

**Comment by CHN-STUDENT** [comment]
我查阅一些资料貌似可以通过`df -P . | tail -1 | awk '{print $4}'`输出目录可用的空间。
https://unix.stackexchange.com/questions/6008/get-the-free-space-available-in-current-directory-in-bash
https://linux.die.net/man/1/du
判断目录的大小可以通过`du -sb /www | awk '{ print $1 }'`来实现。
https://stackoverflow.com/questions/5920333/how-to-check-size-of-a-file

**Comment by vcheckzen** [comment]
`df` 与 `du -b` 单位不同，会导致比较错误，请检验是否需将 `b` 去掉

**Comment by CHN-STUDENT** [comment]
@vcheckzen 我刚使用df -kP 和du -K统一了单位，前辈是否更好的方案？
